apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels: {"app": "nginx"}
    spec:
      containers:
      - name: nginx
        image: gcr.io/googleproject/nginx:p4
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "3300m"
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /
            port: 80
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool